name: yiwumart

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.6+20

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  webview_flutter: ^3.0.4
  dio: ^4.0.6
  http: ^0.13.5
  photo_view: ^0.14.0
  cached_network_image: ^3.2.2
  share_plus: ^6.3.0
  shimmer: ^2.0.0
  firebase_core: ^2.3.0
  flutter_local_notifications: ^12.0.4
  firebase_messaging: ^14.1.2
  permission_handler: ^10.2.0
  connectivity_plus: ^3.0.2
  internet_connection_checker: ^1.0.0+1
  async: ^2.9.0
  flutter_screenutil: ^5.6.0
  avatars: ^3.0.2
  flutter_svg: ^1.1.6
  flutter_form_builder: ^7.7.0
  upgrader: ^6.0.1
  expandable_text: ^2.3.0
  flutter_html: ^3.0.0-alpha.6
  font_awesome_flutter: ^10.4.0
  flutter_bloc: ^8.1.2
  package_info_plus: ^3.0.3
  badges: ^3.0.3
  equatable: ^2.0.5
  flutter_datetime_picker: ^1.5.1
  intl_phone_field: ^3.1.0
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  device_info_plus: ^8.2.0
  flutter_slidable: ^2.0.0
  pin_code_fields: ^7.4.0
  dropdown_button2: ^2.3.9
  smooth_page_indicator: ^1.1.0
  group_button: ^5.3.3
  flutter_multi_formatter: ^2.11.9
  loader_overlay: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/img/
    - assets/icons/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Black.ttf
        - asset: assets/fonts/NotoSans-BlackItalic.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
        - asset: assets/fonts/NotoSans-ExtraBold.ttf
        - asset: assets/fonts/NotoSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/NotoSans-ExtraLight.ttf
        - asset: assets/fonts/NotoSans-ExtraLightItalic.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
        - asset: assets/fonts/NotoSans-Light.ttf
        - asset: assets/fonts/NotoSans-LightItalic.ttf
        - asset: assets/fonts/NotoSans-Medium.ttf
        - asset: assets/fonts/NotoSans-MediumItalic.ttf
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-SemiBold.ttf
        - asset: assets/fonts/NotoSans-SemiBoldItalic.ttf
        - asset: assets/fonts/NotoSans-Thin.ttf
        - asset: assets/fonts/NotoSans-ThinItalic.ttf
    - family: Tinkoff
      fonts:
        - asset: assets/fonts/TinkoffSans.ttf
        - asset: assets/fonts/TinkoffSans_Bold.ttf
        - asset: assets/fonts/TinkoffSans_Medium.ttf

  uses-material-design: true

